FROM ghcr.io/linuxserver/baseimage-kasmvnc:kali

# title
ENV TITLE="Kali Linux"

RUN \
  echo "**** add icon ****" && \
  curl -o \
    /kclient/public/icon.png \
    https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/kali-logo.png && \
  echo "**** install packages ****" && \
  apt-get update && \
  DEBIAN_FRONTEND=noninteractive \
  apt-get install -y --no-install-recommends \
    autopsy \
    cutycapt \
    dirbuster \
    dolphin \
    faraday \
    fern-wifi-cracker \
    guymager \
    gwenview \
    hydra \
    kali-desktop-kde \
    kali-linux-default \
    kali-tools-top10 \
    kate \
    kde-config-gtk-style \
    kdialog \
    kfind \
    khotkeys \
    kio-extras \
    knewstuff-dialog \
    konsole \
    ksystemstats \
    kwin-addons \
    kwin-x11 \
    legion \
    ophcrack \
    ophcrack-cli \
    plasma-desktop \
    plasma-workspace \
    qml-module-qt-labs-platform \
    sqlitebrowser \
    systemsettings && \
  echo "**** kde tweaks ****" && \
  sed -i \
    's/applications:org.kde.discover.desktop,/applications:org.kde.konsole.desktop,/g' \
    /usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/config/main.xml && \
  echo "**** cleanup ****" && \
  apt-get autoclean && \
  rm -rf \
    /config/.cache \
    /var/lib/apt/lists/* \
    /var/tmp/* \
    /tmp/*

# Ensure gedit is installed
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    python3 \
    python3-pip \
    python3-tk \
    gedit \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# add local files
COPY /root /
COPY /fyp.py /config/Desktop/fyp.py
COPY /beginnerInstruction.txt /config/Desktop/beginnerInstruction.txt
COPY /tut.txt /config/Desktop/tut.txt

ENV PYTHONUNBUFFERED=1

# Setup permissions
RUN mkdir -p /tmp/.X11-unix && chmod 1777 /tmp/.X11-unix && \
    chmod 777 /config/Desktop && \
    chmod 777 /config/Desktop/fyp.py && \
    chmod 777 /config/Desktop/beginnerInstruction.txt && \
    chmod 777 /config/Desktop/tut.txt
RUN gzip -d /usr/share/wordlists/rockyou.txt.gz

# ports and volumes
EXPOSE 3000
VOLUME /config
