# Generated by Django 5.1 on 2024-11-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupannouncement',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='announcements/pdfs/'),
        ),
    ]
