# Generated by Django 5.1 on 2024-11-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_groupannouncement_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupannouncement',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='groupannouncement',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='announcements/attachment/'),
        ),
    ]
