# Generated by Django 5.1 on 2024-11-10 08:28

import group.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_groupannouncement_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupannouncement',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='groupannouncement',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='announcements/files/', validators=[group.models.validate_file_extension]),
        ),
    ]
