# Generated by Django 5.1 on 2024-11-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_remove_groupannouncement_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupannouncement',
            name='attachment',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='announcements/attachment/'),
        ),
    ]
