# Generated by Django 5.1 on 2024-11-10 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_remove_groupannouncement_attachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupannouncement',
            name='pdf_file',
        ),
        migrations.CreateModel(
            name='AnnouncementAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='announcements/pdfs/')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='group.groupannouncement')),
            ],
        ),
    ]
