# Generated by Django 5.1 on 2024-11-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_remove_groupannouncement_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupannouncement',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='announcements/pdfs/'),
        ),
        migrations.DeleteModel(
            name='AnnouncementAttachment',
        ),
    ]
