# Generated by Django 5.1 on 2024-11-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_remove_groupannouncement_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementattachment',
            name='file_type',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
