# Generated by Django 5.1.3 on 2024-12-01 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='description',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='time_limit',
        ),
    ]
