# Generated by Django 5.1.3 on 2024-12-01 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0002_remove_level_description_remove_scenario_time_limit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['-difficulty']},
        ),
    ]
