# Generated by Django 5.1.3 on 2024-12-01 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0003_alter_level_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['id']},
        ),
    ]
