# Generated by Django 5.1.4 on 2024-12-10 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0004_alter_level_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='level',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='level',
            name='scenario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='level', to='scenario.scenario'),
        ),
    ]
